sudo: required # 관리자 권한 갖기
language: generic # 언어(플랫폼)을 선택 -> 뭐지 generic이
branches:
  only:
    - main
services: # 도커환경구성
  - docker

before_install: # 스크립트 실행할 수 있는 환경구성
  - echo "start creating image with 도커파일"
  - docker build -f Dockerfile.dev ./ -t docker-react-app

script: # 실행할 스크립트
  - docker run -e CI=true docker-react-app yarn run test -- --coverage

deploy:
  provider: elasticbeanstalk # 외부 서비스 표시(s3, elasticbeanstalk, firebase 등등)
  region: ap-northeast-2 # aws 리전
  app: docker-react-app-aws # Elastic BeanStalk application 이름
  env: Dockerreactappaws-env # Elastic BeanStalk > All applications > Environments
  bucket_name: elasticbeanstalk-ap-northeast-2-984774476028 # Elastic BeanStalk 에서 사용중인 s3버킷이름
  bucket_path: docker-react-app-aws # 애플리케이션 이름과 동일하게 넣으면 된다. 파일이 저장될 경로
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY

after_suceess:
  - echo "Test Success"
